### ISSUE TITLE
Launch script

### ISSUE THREAD

**Issue by LorenzoPeri17** [giusSacco/ADR#12]
Questa è una cosa mia, ma mi turba il cervello dover cambiare i valori in un file di testo per lanciare una nuova simulazione. Se ne vuoi mandare tante in parallelo è una race condition che aspetta di esplodere (vedi figura sbagliata sulla mia tesi e cagata annessa che ho scritto per giustificarla😂)
Un'interfaccia che mi piacerebbe di più è che tutto fosse un processo di python chiamato da un multiprocessing.Master (che è thread safe)
Appena ho tempo faccio una nuova branch e ti faccio vedere cosa intendo :)

**Comment by giusSacco** [comment]
Ci pensavo anche io a questa cosa! Una cosa carina sarebbe dare in pasto un array di frequenze (stessa cosa con alpha_0 ed il vento costante) e poi chiamare ADR.py con un altro programma. Mi ricordo che avevamo fatto qualcosa di simile con Bloino ma non saprei così su due piedi sinceramente quindi se tu hai una vaga idea va benissimo!
